### ISSUE TITLE
unable to load broker ui

### ISSUE THREAD

**Issue by travi** [DiUS/pact_broker-docker#10]
After getting the docker container up and running and connecting to the database, I'm now left with a message of `Not Found: /` (similar for other routes). 

I am not very strong with ruby or passenger, so I'm not very sure where to start to debug the issue. `docker logs` shows the database setup and what appears to be successful loading of several components, including the UI.

I have deployed the non-containerized broker to heroku for a different project without issue, but expected the container to be even simpler. Could you help me understand where to start looking?

**Comment by IschenkoArtem** [comment]
I have the same issue.
When I launch docker image with port assignment like this `-p 8034:80` then broker responses with `Not Found: /`, though I can see that it successfully migrates DB and I can open HAL browser (that is empty for the same reason).

If I start  docker like this `-p 80:80` than everything works perfectly.

**Comment by bethesque** [comment]
I discovered this the other day. The docker image needs to be mapped to port 80, otherwise the Rack Map middleware thinks that the incoming request is not for it, and responds with a 404. I do not know if this is a bug in the Rack middlware or not because I wouldn't have thought it should know or care about ports. This is the line that causes it to fail:

https://github.com/rack/rack/blob/master/lib/rack/urlmap.rb#L53

The problem is, with `-p 8034:80`, the ports are being forwarded, but the HTTP request headers are not being rewritten.

**Comment by travi** [comment]
Ah, that makes sense. Than you for the responses. It sounds like nginx or similar would be necessary in front of this container. This issue could probably be closed out with an addition to the readme to give consumers a heads up about this situation.

**Comment by bethesque** [comment]
I've put a note in the readme. If it becomes more of an issue, I'll see whether it is a Rack bug or not.
