### ISSUE TITLE
Recommended version of PostgreSQL?

### ISSUE THREAD

**Issue by zharvey-welltok** [DiUS/pact_broker-docker#38]
Hi, looking at Docker's [official PostgreSQL repo](https://hub.docker.com/_/postgres/) I'm seeing a wide variety of supported tags ranging from 9.2.* to 9.6.*.

Just wondering: **Is there a recommended version of Postgres that the community has for this Docker image?**

**Comment by bethesque** [comment]
The safest one to use would be the version that travis-ci installs by default, as that's the one that the tests run against. According to their [documentation](https://docs.travis-ci.com/user/database-setup/) "The Travis CI build environments use version 9.1 by default".

We should possibly look at upgrading that if the docker containers start at 9.2.

**Comment by bethesque** [comment]
Ok, I tried out travis with 9.6 and it [blew up](https://travis-ci.org/pact-foundation/pact_broker/jobs/239012060) (travis configuration problem, not a code problem) so I tried with 9.5, and it [passed](https://travis-ci.org/pact-foundation/pact_broker/builds/239012781), so I'd say that we officially support 9.5. Having said that, I know 9.6 works because that's what I'm running locally ;)

**Comment by zharvey-welltok** [comment]
Thanks @bethesque ! Appreciate the follow-through!
