### ISSUE TITLE
@bethesque , Any help on nginx ? or can i get without nginx configuration docker image in separate branch? 

### ISSUE THREAD

**Issue by itsmenandess** [DiUS/pact_broker-docker#67]
Our Kubernetes Team increased the security level blueprint 1.7.2. So our current deployment getting failed. i am not able to sort out it further. 

Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
Running /etc/my_init.d/30_presetup_nginx.sh...
Running /etc/rc.local...
Booting runit daemon...
Runit started as PID 11
ok: run: /etc/service/nginx-log-forwarder: (pid 21) 0s
chown: changing ownership of '/dev/xconsole': Operation not permitted
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2018/03/14 09:10:29 [emerg] 19#19: chown("/var/lib/nginx/body", 33) failed (1: Operation not permitted)
tail: cannot open '/var/log/nginx/error.log' for reading: Permission denied
ok: run: /etc/service/nginx-log-forwarder: (pid 28) 0s
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2018/03/14 09:10:30 [emerg] 32#32: chown("/var/lib/nginx/body", 33) failed (1: Operation not permitted)
tail: cannot open '/var/log/nginx/error.log' for reading: Permission denied

**Comment by bethesque** [comment]
I'm sorry @itsmenandess, this problem pertains to nginx, rather than the pact broker code. You'd be best asking this question in an nginx forum, as I'm afraid I am no nginx expert. It's possible that @mefellows may have some idea.

**Comment by mefellows** [comment]
@itsmenandess the nginx configuration is very configurable. You can simply replace the configuration with your own, or augment it, with the usual docker volume/file sharing mechanisms. In fact, _you could completely disable it and bypass it altogether_ with a little effort.

Look at the [source code](https://github.com/DiUS/pact_broker-docker/blob/master/container/etc/nginx/sites-enabled/webapp.conf) to see the file we update, and you can also run the container locally to see the other default nginx files.

I'm guessing the problem is that nginx wants to write to a (location on a) filesystem that is now no longer writable to the container - you need your "Kubernetes Team" to fix it or provide you with an alternative.

This request is too specific to your deployment topology, and I'm going to close it off.
